-- Polyculy Database Schema (H2 / MSSQLServer mode)
-- ============================================================

-- Users
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    timezone_id VARCHAR(100) NOT NULL DEFAULT 'America/New_York',
    calendar_created BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Licences
CREATE TABLE IF NOT EXISTS licences (
    licence_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licence_code VARCHAR(50) NOT NULL UNIQUE,
    licence_type VARCHAR(20) NOT NULL DEFAULT 'purchased',
    pack_id INT,
    owner_user_id INT,
    gifted_to_email VARCHAR(255),
    gifted_by_user_id INT,
    redeemed_by_user_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    redeemed_at TIMESTAMP,
    CONSTRAINT fk_lic_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lic_gifted_by FOREIGN KEY (gifted_by_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lic_redeemed FOREIGN KEY (redeemed_by_user_id) REFERENCES users(user_id)
);

-- Connections
CREATE TABLE IF NOT EXISTS connections (
    connection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_1 INT,
    user_id_2 INT,
    status VARCHAR(40) NOT NULL DEFAULT 'awaiting_signup',
    invited_email VARCHAR(255),
    invited_display_name VARCHAR(100),
    initiated_by INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_conn_u1 FOREIGN KEY (user_id_1) REFERENCES users(user_id),
    CONSTRAINT fk_conn_u2 FOREIGN KEY (user_id_2) REFERENCES users(user_id),
    CONSTRAINT fk_conn_init FOREIGN KEY (initiated_by) REFERENCES users(user_id)
);

-- Connection Display Preferences
CREATE TABLE IF NOT EXISTS connection_display_prefs (
    pref_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    target_user_id INT NOT NULL,
    nickname VARCHAR(100),
    avatar_override VARCHAR(500),
    calendar_color VARCHAR(7) NOT NULL DEFAULT '#7C3AED',
    CONSTRAINT fk_cdp_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_cdp_target FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

-- Personal Events
CREATE TABLE IF NOT EXISTS personal_events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    all_day BOOLEAN NOT NULL DEFAULT FALSE,
    timezone_id VARCHAR(100) NOT NULL DEFAULT 'America/New_York',
    event_details CLOB,
    address VARCHAR(500),
    reminder_minutes INT,
    visibility_tier VARCHAR(20) NOT NULL DEFAULT 'invisible',
    is_cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pe_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id)
);

-- Personal Event Visibility
CREATE TABLE IF NOT EXISTS personal_event_visibility (
    visibility_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    target_user_id INT NOT NULL,
    visibility_type VARCHAR(20) NOT NULL,
    snapshot_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pev_event FOREIGN KEY (event_id) REFERENCES personal_events(event_id),
    CONSTRAINT fk_pev_target FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

-- Shared Events
CREATE TABLE IF NOT EXISTS shared_events (
    shared_event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_user_id INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    all_day BOOLEAN NOT NULL DEFAULT FALSE,
    timezone_id VARCHAR(100) NOT NULL DEFAULT 'America/New_York',
    event_details CLOB,
    address VARCHAR(500),
    reminder_minutes INT,
    reminder_scope VARCHAR(5) NOT NULL DEFAULT 'me',
    participant_visibility VARCHAR(10) NOT NULL DEFAULT 'visible',
    global_state VARCHAR(20) NOT NULL DEFAULT 'tentative',
    cancellation_reason VARCHAR(50),
    ownership_transfer_active BOOLEAN NOT NULL DEFAULT FALSE,
    ownership_transfer_deadline TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_se_organizer FOREIGN KEY (organizer_user_id) REFERENCES users(user_id)
);

-- Shared Event Participants
CREATE TABLE IF NOT EXISTS shared_event_participants (
    participant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    user_id INT NOT NULL,
    attendance_type VARCHAR(10) NOT NULL DEFAULT 'required',
    response_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    is_one_hop BOOLEAN NOT NULL DEFAULT FALSE,
    link_person_user_id INT,
    one_hop_consent_given BOOLEAN NOT NULL DEFAULT FALSE,
    one_hop_activated BOOLEAN NOT NULL DEFAULT FALSE,
    is_removed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sep_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id),
    CONSTRAINT fk_sep_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_sep_link FOREIGN KEY (link_person_user_id) REFERENCES users(user_id)
);

-- Proposals
CREATE TABLE IF NOT EXISTS proposals (
    proposal_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    proposer_user_id INT NOT NULL,
    proposed_start TIMESTAMP NOT NULL,
    proposed_end TIMESTAMP NOT NULL,
    message CLOB,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prop_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id),
    CONSTRAINT fk_prop_user FOREIGN KEY (proposer_user_id) REFERENCES users(user_id)
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(300) NOT NULL,
    message CLOB,
    related_entity_type VARCHAR(30),
    related_entity_id INT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Notification Preferences
CREATE TABLE IF NOT EXISTS notification_preferences (
    pref_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_mode VARCHAR(10) NOT NULL DEFAULT 'instant',
    quiet_hours_start VARCHAR(5),
    quiet_hours_end VARCHAR(5),
    CONSTRAINT fk_np_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Audit Log
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INT,
    action_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(30) NOT NULL,
    entity_id INT,
    details CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(user_id)
);

-- Informational Emails
CREATE TABLE IF NOT EXISTS informational_emails (
    info_email_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_event_id INT NOT NULL,
    sender_user_id INT NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    recipient_name VARCHAR(100),
    message_note CLOB,
    is_claimed BOOLEAN NOT NULL DEFAULT FALSE,
    claimed_by_user_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ie_event FOREIGN KEY (shared_event_id) REFERENCES shared_events(shared_event_id),
    CONSTRAINT fk_ie_sender FOREIGN KEY (sender_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_ie_claimed FOREIGN KEY (claimed_by_user_id) REFERENCES users(user_id)
);

-- CSRF Tokens
CREATE TABLE IF NOT EXISTS csrf_tokens (
    token_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL,
    token VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Calendar Toggle State (for Mine/Our persistence)
CREATE TABLE IF NOT EXISTS calendar_toggle_state (
    toggle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    target_user_id INT NOT NULL,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_cts_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_cts_target FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS ix_conn_u1 ON connections(user_id_1);
CREATE INDEX IF NOT EXISTS ix_conn_u2 ON connections(user_id_2);
CREATE INDEX IF NOT EXISTS ix_conn_status ON connections(status);
CREATE INDEX IF NOT EXISTS ix_conn_email ON connections(invited_email);
CREATE INDEX IF NOT EXISTS ix_pe_owner ON personal_events(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_pe_start ON personal_events(start_time);
CREATE INDEX IF NOT EXISTS ix_pev_event ON personal_event_visibility(event_id);
CREATE INDEX IF NOT EXISTS ix_se_organizer ON shared_events(organizer_user_id);
CREATE INDEX IF NOT EXISTS ix_se_state ON shared_events(global_state);
CREATE INDEX IF NOT EXISTS ix_sep_event ON shared_event_participants(shared_event_id);
CREATE INDEX IF NOT EXISTS ix_sep_user ON shared_event_participants(user_id);
CREATE INDEX IF NOT EXISTS ix_prop_event ON proposals(shared_event_id);
CREATE INDEX IF NOT EXISTS ix_notif_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS ix_notif_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS ix_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_date ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS ix_lic_code ON licences(licence_code);
CREATE INDEX IF NOT EXISTS ix_lic_status ON licences(status);
